addSbtPlugin("me.rschatz"           % "npt"                  % "0.2.0")
addSbtPlugin("net.virtual-void"     % "sbt-dependency-graph" % "0.8.2")
addSbtPlugin("com.eed3si9n"         % "sbt-dirty-money"      % "0.1.0")
addSbtPlugin("com.timushev.sbt"     % "sbt-updates"          % "0.1.10")
addSbtPlugin("com.orrsella"         % "sbt-stats"            % "1.0.5")
//addSbtPlugin("io.get-coursier"      % "sbt-coursier"         % "1.0.0-M15")
